#OpenApi Spec 3.0.3 to EBNF
#OpenApi Docs Url : https://spec.openapis.org/oas/v3.0.3#relative-references-in-urls
# Docs Page : 4.7.1
OpenApiDocFormat := "JSON" | "YAML"
OpenAPIDocFields := OpenAPIVersion Info [Servers] Paths [Components SecurityRequirement Tags ExternalDocs]
# Field name : openapi
OpenAPIVersion := <STRING>

# 4.7.2 info
Info := InfoObj
InfoObj := Title [ Description TermsOfService Contact License ] Version
Title := <STRING>
Description := <STRING>
TermsOfService := <STRING>
Contact := ContactObj 
License := LicenseObj
Version := <STRING>
ContactObj := [Name Url Email] # 4.7.3 Contact Object
LicenseObj := Name Url? # 4.7.4 License Object
Name := <STRING>
Url := <STRING>
Email := <STRING>

# 4.7.5 Servers
Servers := ServerObj
ServerObj := Url [Description Variable]

# 4.7.6 Server Variable Object
Variable := ServerVariableObj
ServerVariableObj := Enum? Default Description?
Enum := "array" <STRING>
Default : <STRING>

# 4.7.8 paths
Paths := PathsObject*
PathsObject := ("/"<IDENT>) PathItemObject 
PathItemObject :=  ["$ref" Summary Description Get Put Post Delete Options Head Patch Trace PathServers Parameters] # 4.7.9 Path Item Object
"$ref" := <STRING>
Summary := <STRING>
Get := OperationObject
Put := OperationObject
Post := OperationObject
Delete := OperationObject
Options := OperationObject
Head := OperationObject
Patch := OperationObject
Trace  := OperationObject
PathServers := ServerObj*
Parameters := ParameterObj | ReferenceObj
SchemaObj := [Nullable Discriminator ReadOnly WriteOnly Xml ExternalDocs Example Deprecated] #4.7.24 Schema Object 

# 4.7.10 Operation Object
OperationObject := [OperationTags Summary Description ExternalDocs OperationId Parameters RequestBody] Responses [Callbacks Deprecated Security Servers]
# 4.7.12 Parameter Object
ParameterObj := Name locationOfParameter [Description Required Deprecated AllowEmptyValue Style Explode AllowReserved Schema Example Examples]
ReferenceObj := "$ref" # 4.7.23 Reference Object
OperationTags := "array" <STRING>
ExternalDocs := ExternalDocsObj # 4.7.11 External Documentation Object
ExternalDocsObj := Description? Url
OperationId := <STRING>

LocationOfParameter := "query" | "header" | "path" | "cookie" #In
Required := <BOOLEAN>
Deprecated := <BOOLEAN>
AllowEmptyValue := <BOOLEAN>
Style := <STRING> ": " StyleValues
Explode := <BOOLEAN>
AllowReserved := <BOOLEAN>
Schema := SchemaObj | ReferenceObj
Example := <ANY>
Examples := <IDENT> (ExampleObj | ReferenceObj)
ExampleObj := [Summary Description Value ExternalValue] # 4.7.19 Example Object 
Value := <ANY>
# 4.7.12.3 Style Values
StyleValues := Matrix | Labal | Form | Simple | SpaceDelimited | PipeDelimited | DeepObject
Matrix := MatrixType MatrixIn
Labal := LabalType LabalIn
Form := FormType FormIn
Simple := SimpleType SimpleIn
SpaceDelimited := SpaceDelimitedType SpaceDelimitedIn
PipeDelimited := PipeDelimitedType PipeDelimitedIn
DeepObject := DeepObjectType DeepObjectIn
MatrixType := "primitive", "array", "object"
MatrixIn := "path"
LabalType := "primitive", "array", "object"
LabalIn := "path"
FormType := "primitive", "array", "object"
FormIn := "query", "cookie"
SimpleType := "array"
SimpleIn := "path", "header"
SpaceDelimitedType := "array"
SpaceDelimitedIn := "query"
PipeDelimitedType := "array"
PipeDelimitedIn := "query"
DeepObjectType := "object"
DeepObjectIn := "query"

Nullable := <BOOLEAN>
Discriminator := DiscriminatorObj
ReadOnly := <BOOLEAN>
WriteOnly := <BOOLEAN>
Xml := XmlObj
DiscriminatorObj := PropertyName Mapping? # 4.7.25 Discriminator Object 
XmlObj := [Name NameSpace Prefix Attribate Wrapped] # 4.7.26 XML Object
Mapping := <STRING> ":" <STRING> 
NameSpace := Url
Prefix := <STRING>
Attribate := <BOOLEAN>
Wrapped := <BOOLEAN>

# 4.7.7 Components Object
Components := ComponentsObj *
ComponentsObj := <IDENT> [Schemas Responses Parameters Examples RequestBodies Headers SecuritySchemes Links Callbacks]
# 4.7.16 Responses Object 
Responses := ResponsesObj
ResponsesObj := ("default" | HTTPStatusCode) ResponsesType
ResponsesType := (ResponseObj | ReferenceObj)*
RequestBody := RequestBodyObj | ReferenceObj

ResponseObj := Description (<IDENT> [Headers Content Links]) # 4.7.17 Response Object 
Headers := HeaderObj | ReferenceObj
Content := MediaTypeObj
Links := LinkObj | ReferenceObj
# 4.7.27 Security Scheme Object
SecuritySchemes := SecuritySchemeObj
SecuritySchemeObj := Type Description? Name In Scheme BearerFormat? Flows OpenldConnectUrl
Flows := OAuthFlowsObj ApliesTo "ANY"

# 4.7.28 OAuth Flows Object
OAuthFlowsObj := [Implicit Password ClientCredentials AuthorizationCode]
Implicit := OAuthFlowObj
Password := OAuthFlowObj
ClientCredentials := OAuthFlowObj
AuthorizationCode := OAuthFlowObj
# 4.7.29 OAuth Flow Object 
OAuthFlowObj := AuthorizationUrl TokenUrl RefreshUrl? Scopes
AuthorizationUrl := AuthorizationUrlType AuthorizationUrl
TokenUrl := TokenUrlType TokenUrlApliesTo
RefreshUrl := RefreshUrlType RefreshUrlApliesTo
Scopes := ScopesType ScopesApliesTo

AuthorizationUrlType := <STRING>
AuthorizationUrl := "oauth2 (implicit, authorizationCode)"
TokenUrlType := <STRING>
TokenUrlApliesTo := "oauth2 (password, clientCredentials, authorizationCode)"
RefreshUrlType := <STRING>
RefreshUrlApliesTo := "oauth2"
ScopesType := <STRING> ":" <STRING>
ScopesApliesTo := "oauth2"
# 4.7.20 Link Object
LinkObj := [OperationRef OperationId LinkParameters LinkRequestBody Description Server]
OperationRef := <STRING>
LinkParameters := <IDENT> (<ANY> | <EXPRESSION>)
LinkRequestBody := <ANY> | <EXPRESSION>
Server := ServerObj
Callbacks := <EXPRESSION> PathItemObject # 4.7.18 Callback Object

HeaderObj := [Description Required Deprecated AllowEmptyValue Style Explode AllowReserved Schema Example Examples] # 4.7.21 Header Object
MediaTypeObj := [Schema Example Examples Encoding] # 4.7.14 Media Type Object
Encoding := <IDENT> EncodingObj # 4.7.15 Encoding Object 
EncodingObj := [ContentType (<IDENT> Headers) Style Explode AllowReserved]
ContentType := <STRING>

RequestBodyObj := Description? Content Required? # 4.7.13 Request Body Object

# 4.7.30 Security Requirement Object
SecurityRequirement := SecurityRequirementObj
SecurityRequirementObj := <IDENT> ("array" <STRING>)
# 4.7.22 Tag Object
Tags := TagObj 
TagObj := Name [Description ExternalDocs]
